name: API Automation with Newman

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  newman-api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd api-test
          npm install

      - name: Run API tests with Newman
        run: |
          cd api-test
          npx newman run "QA API Automation.postman_collection.json" \
            -e environment.json \
            -r cli,htmlextra

      - name: Upload Newman HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: api-test/newman/*.html
          if-no-files-found: warn